export const list = [
  { icon: "🏠", text: "Home" },
  { icon: "🎮", text: "DEV++" },
  { icon: "🎙️", text: "Podcasts" },
  { icon: "📽️", text: "Videos" },
  { icon: "🏷️", text: "Tags" },
  { icon: "💡", text: "DEV Help" },
  { icon: "🛍️", text: "Forem Shop" },
  { icon: "💖", text: "Advertise on DEV" },
  { icon: "🏆", text: "DEV Challenges" },
  { icon: "✨", text: "DEV Showcase" },
  {
    icon: <img src="../original_logo.png" alt="About" className="w-6 h-6" />,
    text: "About",
  },
  { icon: "🎷", text: "Contact" },
  { icon: "🐘", text: "Free Postgres Database" },
  { icon: "📒", text: "Guides" },
  { icon: "🤔", text: "Software comparisons" },
];
export const list2 = [
  { icon: "👍", text: "Code of Conduct" },
  { icon: "🤓", text: "Privacy Policy" },
  { icon: "👀", text: "Terms of use" },
];

export const list3 = [
  "#webdev",
  "#javascript",
  "#beginners",
  "#programming",
  "#tutorial",
  "#react",
  "#python",
  "#ai",
  "#devops",
  "#productivity",
  "#opensource",
  "#aws",
  "#css",
  "#node",
  "#typescript",
  "#career",
  "#java",
  "#news",
  "#learning",
  "#machinelearning",
  "#cloud",
  "#html",
  "#database",
  "#discuss",
  "#nextjs",
  "#kubernetes",
  "#php",
  "#docker",
  "#dotnet",
  "#datascience",
];

export const list4 = [
  "9 open-source gems to become the ultimate developer🔥 🚀",
  "10 Things You Can Learn from Netflix’s Architecture",
  "Global Talent Visa: How to Move to the UK Without an Employer",
  "Why React Won the Front-End Race",
  "50 Must-Know VS Code Extensions for Faster Development 🚀",
  "10 Developer Tools to Improve Your Daily Life as a Developer",
  "Understanding the Linux Filesystem: An In-Depth Guide for DevOps Engineers",
  "DevOps Project - The Ultimate CICD Corporate DevOps Pipeline Project",
  "Beginner’s Guide to Freelancing",
  "Mastering SOLID Principles in React: Elevating Your Code Quality",
  "Frontend Dev + Data Structures & Algorithms: How DSA Can Power Your React App ⚡",
  "How to Build Frontend Apps 10x Faster",
  "How to implement a Distributed Lock using Redis",
  "7 BEST VS Code Extensions for Faster Development — 2024 Edition 🚀",
  "Using Cursor + Claude to Make Full-Stack SaaS Apps",
  "DevOps Basics reaches 200 stars: A milestone celebration 🎉",
  "Do You Still Use Git in the Terminal?",
  "How ts-pattern can improve your code readability?",
  "End-to-End DevOps Project: Building, Deploying, and Monitoring a Full-Stack Application",
  "DevOps for Beginners: A Complete Roadmap to Get Started",
  "recently queried",
];
